name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Pull the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false
      - name: Prepare env
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
          ca-certificates \
          clang \
          cmake \
          git \
          make
          git clone https://github.com/google/googletest.git -b release-1.11.0 && \
          cd googletest && \
          mkdir build && \
          cd build && \
          cmake .. && \
          make && \
          sudo make install && \
          cd ../../ && \
          rm -rf googletest
          git clone https://github.com/google/glog.git && \
          cd glog && \
          git checkout v0.6.0 && \
          cmake -S . -B build -G "Unix Makefiles" && \
          cmake --build build && \
          sudo cmake --build build --target install && \
          cd ../ && \
          rm -rf glog && \
          sudo ldconfig
      - name: Build library
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd build/tests
          ctest